import type { Metadata } from "next";
import { Geist, Geist_Mono, Quantico } from "next/font/google";

import "./globals.css";
import "highlight.js/styles/atom-one-dark.css";

import TopBar from "@/components/TopBar";

const quantico = Quantico({ weight: ["400", '700'], subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={`${quantico.className} h-dvh antialiased`}>
				<TopBar />
				{children}
			</body>
		</html>
	);
}
